on:
  pull_request:
    paths:
    - '**.tf'
    - '**.tfvars'
    - '**.tfvars.json'
jobs:
  infracost:
    runs-on: ubuntu-latest
    name: Show infracost diff
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Run infracost diff
      uses: infracost/infracost-gh-action@master # Use a specific version instead of master if locking is preferred
      env:
        INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      with:
        path: .
        terraform_plan_flags: -var-file=my.tfvars -var="subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}" -var="avx_aviatrix_customer_id=${{ secrets.AVX_CUSTOMER_ID }}" -var="avx_account_email=${{ secrets.ADMIN_EMAIL }}" -var="avx_controller_admin_email=${{ secrets.ADMIN_EMAIL }}"