name: Check terraform
on:
  - pull_request
jobs:
  format_terraform:
    runs-on: ubuntu-latest
    name: format-terraform
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }} 

          # https://github.com/dflook/terraform-fmt
      - name: terraform fmt
        uses: dflook/terraform-fmt@v1

      - name: push-changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add --all
          git commit -m "terraform-fmt: automated action" || echo "No changes to commit"
          git push

  document_terraform:
    runs-on: ubuntu-latest
    name: document-terraform
    needs: [format_terraform]
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

        # https://github.com/terraform-docs/gh-actions
      - name: render-terraform-module-docs
        uses: terraform-docs/gh-actions@main
        with:
          find-dir: .
          output-file: MODULE_README.md
          output-method: inject
          git-push: "true"
